# Copyright (c) Jiaqi Liu.
---
name: Documentation CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  documentation-ci-cd:
    name: Documentation CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install sphinx
          pip install sphinx_gallery
          pip install sphinx-prompt
          pip install sphinxext-opengraph
          pip install sphinx-copybutton
          pip install pydata-sphinx-theme
          pip install sphinxcontrib-sass
          pip install sphinx-design
          pip install sphinx-remove-toctrees
          pip install sphinx-gallery
          pip install scipy
          pip install pandas
          pip install seaborn
          pip install memory_profiler
          pip install Pillow
          pip install pooch
          pip install plotly
          pip install matplotlib
          pip install Cython
          pip install numpy
          pip install numpydoc
          pip install scikit-image
          pip install pytest
          pip install matplotlib
          pip install Pillow
          pip install pandas
          pip install polars
          pip install packaging
      - name: Install scikit-learn from source
        run: pip install .
      - name: Build docs
        run: make html
        working-directory: doc
      - name: Load CNAME
        run: echo scikit-learn.qubitpi.org > doc/_build/html/stable/CNAME
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html/stable
          user_name: QubitPi
          user_email: jack20220723@gmail.com
